<?php $images = $this->getImages() ?>
<?php $fullscreen = $this->getFullscreen() ?>
<?php if(count($images)>0): ?>
	<?php $links = $this->getLinks() ?>
	<?php $blockId = rand() . time(); ?>
	<?php $animated = $this->getAnimateSlider(); ?>
	<?php if($fullscreen): ?>
		<div class="row fullscreen-slider">
	<?php endif ?>
		<div id="mgs-slider-<?php echo $blockId ?>" class="slider_mgs_carousel owl-carousel">
			<?php foreach($images as $key=>$image): ?>
				<?php if($fullscreen): ?>
					<div class="item fullscreen" <?php if(isset($links[$key]) && ($links[$key]!='')): ?>onclick="setLocation('<?php echo $links[$key] ?>')"<?php endif ?> style="background-image:url('<?php echo $image ?>')">
					</div>
				<?php else: ?>
					<div class="item">
						<a href="<?php if(isset($links[$key]) && ($links[$key]!='')): ?><?php echo $links[$key] ?><?php else: ?>javascript:void(0)<?php endif ?>">
							<img src="<?php echo $image ?>" alt=""/>
						</a>
					</div>
				<?php endif ?>
			<?php endforeach ?>
		</div>
	<?php if($fullscreen): ?>
		</div>
	<?php endif ?>
	<script type="text/javascript">
		require([
			'jquery',
			'mgs/owlcarousel'
		], function(jQuery){
			(function($) {
				<?php if($fullscreen): ?>
					$(".fullscreen-slider").height($(window).height());
					
					$(window).resize(function() {
						$(".fullscreen-slider").height($(window).height());
					});
				<?php endif ?>
				$("#mgs-slider-<?php echo $blockId ?>").owlCarousel({
					items: 1,
					rtl: <?php echo $this->getRightToLeft(); ?>,
					loop: <?php echo $this->getLoop(); ?>,
					nav: <?php echo $this->getControlNav(); ?>,
					dots: <?php echo $this->getControlDots(); ?>,
					autoplayTimeout: <?php echo $this->getAutoSpeed(); ?>,
					autoplay: <?php echo $this->getAutoPlay(); ?>,
					autoplayHoverPause: <?php echo $this->getStopAuto() ? 'true' : 'false'; ?>,
					animateOut: '<?php echo $animated['out'] ?>',
					animateIn: '<?php echo $animated['in'] ?>',
					navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
                    responsive:{
                        0:{
                            nav: false,
                            dots: true
                        },
                        992:{
                            nav: <?php echo $this->getControlNav(); ?>,
                            dots: <?php echo $this->getControlDots(); ?>
                        }
                    }
				});
				
				
			})(jQuery);
		});
	</script>
<?php else: ?>
	<div role="alert" class="alert alert-warning"><?php echo __('There are no sliders matching the selection.') ?></div>
<?php endif ?>